name: Detekt

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Annotate PR with Detekt results
        uses: alaegin/Detekt-Action@v1.23.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          reviewdog_level: error
          reviewdog_filter: file
          reviewdog_reporter: github-pr-review
          detekt_config: detekt/detekt.yml
          detekt_all_rules: false
          detekt_build_upon_default_config: false

      - name: Get changed Kotlin files
        id: changed_kotlin
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep '\.kts\?$' || true)
          if [ -n "$FILES" ]; then
            FORMATTED=$(echo "$FILES" | paste -sd, -)
            echo "Changed Kotlin files: $FORMATTED"
            echo "source_param=-Psource=$FORMATTED" >> $GITHUB_OUTPUT
          else
            echo "No Kotlin files changed"
            echo "source_param=" >> $GITHUB_OUTPUT
          fi

      - name: Get changed Kotlin files via API
        id: changed_kotlin_api
        run: |
          FILES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            | jq -r '.[] | select(.filename | test("\\.kts?$")) | .filename' | paste -sd, -)
      
          if [ -n "$FILES" ]; then
            echo "source_param=-Psource=$FILES" >> $GITHUB_OUTPUT
          else
            echo "source_param=" >> $GITHUB_OUTPUT
          fi


      - name: Run Detekt on changed files
        if: steps.changed_kotlin.outputs.source_param != ''
        run: |
          echo "Running detekt with: ${{ steps.changed_kotlin.outputs.source_param }}"
          ./gradlew detekt ${{ steps.changed_kotlin.outputs.source_param }}
