name: Detekt

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restore local.properties
        env:
          LOCAL_PROPERTIES_BASE64: ${{ secrets.LOCAL_PROPERTIES_BASE64 }}
        run: echo "$LOCAL_PROPERTIES_BASE64" | base64 --decode > local.properties

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Annotate PR with Detekt results
        uses: alaegin/Detekt-Action@v1.23.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          reviewdog_level: error
          reviewdog_filter: file
          reviewdog_reporter: github-pr-review
          detekt_config: detekt/detekt.yml
          detekt_all_rules: false
          detekt_build_upon_default_config: false

      - name: Get changed Kotlin files
        id: changed_files
        run: |
          FILES=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | grep '\.kts\?$' | paste -sd, -)
          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "Changed files: $FILES"

      - name: Run Detekt only on changed files
        if: steps.changed_files.outputs.files != ''
        run: ./gradlew detekt -Psource="${{ steps.changed_files.outputs.files }}"
